cluster:
  version: "v1.23.6+rke2r2"
  name: ""
  domain: ""
  labels: {}
  annotations: {}
  nodepools:
    masters:
      count: 3
      cpus: 2
      vram: 8192
      paused: false
    workers:
      count: 2 
      cpus: 2
      vram: 8192
      paused: false
  vsphere:
    datacenter: "/dc_xxx"
    folder: "/dc_xxx/vm/Rancher"
    pool: "/dc_xxx/host/xxx_cluster/Resources/Rancher"
    datastore: "/dc_xxx/datastore/vol_xxx"
    datastoreCluster: ""
    template: "/dc_xxx/vm/Templates/RHEL8"
    cloudConfig: |-
      #cloud-config
        network:
          version: 2
          ethernets:
            eth0:
              dhcp4: true
    cloudinit: ""
    network:
    - "/dc_xxx/network/net_xxx"
    cfgparam:
    - "disk.enableUUID=TRUE"
    customAttribute: []
    tags: []
 
global:
  cattle:
    systemDefaultRegistry: ""

